version: 2
jobs:
  build:
    working_directory: ~/tabula-api
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Restore m2 caches from previous build
      - restore_cache:
          key: v2-m2-{{ checksum "project.clj" }}
      # Do testing, generate code coverage report, static analysis,
      # check dependency vulnerabilities and compile uberjar
      - run: "lein do \
                  cloverage --codecov, \
                  cljfmt check, kibit, eastwood, bikeshed, \
                  nvd check, uberjar"
      # Store m2 caches for next build
      - save_cache:
          key: v2-m2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      # Upload code coverage report
      - run: bash <(curl -s https://codecov.io/bash)
      # Prepare artifact directories
      - run: "mkdir -p /tmp/artifacts/uberjar && \
              cp \
                  target/tabula-api-$(cat VERSION)-standalone.jar \
                  /tmp/artifacts/uberjar/tabula-api-$(cat VERSION)-standalone.jar"
      # Store the artifact directories
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
