version: '3.2'

volumes:
  m2:
    driver: local

services:
  nginx:
    image: nginx:1.13.2-alpine
    volumes:
      - ${project_root}/.dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${project_root}/.dev/nginx/gzip.conf:/etc/nginx/gzip.conf
    environment:
      # System variables
      TZ: Asia/Hong_Kong
    ports:
      - 34480:80

  clojure:
    image: clojure:lein-2.8.1-alpine
    environment:
      # System variables
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      TZ: Asia/Hong_Kong
      # Application configurations
      HOST: 0.0.0.0
      PORT: 80
    volumes:
      - ${project_root}:/usr/src/app
      - ${project_root}/.dev/lein/profiles.clj:${home}/.lein/profiles.clj
      - m2:${home}/.m2
    working_dir: /usr/src/app
    # Prepare home, user and group via prepare-container helper script
    command: >
      sh -c "/usr/src/app/.dev/scripts/prepare-container \
                ${uid} ${uname} ${gid} ${gname} ${home} && \
            tail -f /dev/null"
    ports:
      # Static port for easily connecting to nREPL session
      - 34487:34487
